ALTER TABLE notifications ADD COLUMN attempt_count INT NOT NULL DEFAULT 0;
ALTER TABLE notifications ADD COLUMN next_attempt_at TIMESTAMP(6) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE notifications ADD COLUMN last_error VARCHAR(2000);