package com.workforceos.scheduling;

public enum NotificationType {
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    OVERTIME_APPROVED,
    OVERTIME_REJECTED,
    SHIFT_SWAP_APPROVED,
    SHIFT_SWAP_REJECTED,
    HANDOVER_SUBMITTED,
    HANDOVER_ACKNOWLEDGED,
    ATTENDANCE_CORRECTION_APPROVED,
    ATTENDANCE_CORRECTION_REJECTED,
    ROSTER_PUBLISHED,
    APPROVAL_PENDING
}
